/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Vacancies service. Represents a row in the &quot;SearchVacanses_Vacancies&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.model.impl.VacanciesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.model.impl.VacanciesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vacancies
 * @see service.model.impl.VacanciesImpl
 * @see service.model.impl.VacanciesModelImpl
 * @generated
 */
public interface VacanciesModel extends BaseModel<Vacancies> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vacancies model instance should use the {@link Vacancies} interface instead.
	 */

	/**
	 * Returns the primary key of this vacancies.
	 *
	 * @return the primary key of this vacancies
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vacancies.
	 *
	 * @param primaryKey the primary key of this vacancies
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id vacancies of this vacancies.
	 *
	 * @return the id vacancies of this vacancies
	 */
	public long getIdVacancies();

	/**
	 * Sets the id vacancies of this vacancies.
	 *
	 * @param idVacancies the id vacancies of this vacancies
	 */
	public void setIdVacancies(long idVacancies);

	/**
	 * Returns the name vacancy of this vacancies.
	 *
	 * @return the name vacancy of this vacancies
	 */
	@AutoEscape
	public String getNameVacancy();

	/**
	 * Sets the name vacancy of this vacancies.
	 *
	 * @param nameVacancy the name vacancy of this vacancies
	 */
	public void setNameVacancy(String nameVacancy);

	/**
	 * Returns the salary of this vacancies.
	 *
	 * @return the salary of this vacancies
	 */
	@AutoEscape
	public String getSalary();

	/**
	 * Sets the salary of this vacancies.
	 *
	 * @param salary the salary of this vacancies
	 */
	public void setSalary(String salary);

	/**
	 * Returns the employer of this vacancies.
	 *
	 * @return the employer of this vacancies
	 */
	@AutoEscape
	public String getEmployer();

	/**
	 * Sets the employer of this vacancies.
	 *
	 * @param employer the employer of this vacancies
	 */
	public void setEmployer(String employer);

	/**
	 * Returns the published_at of this vacancies.
	 *
	 * @return the published_at of this vacancies
	 */
	@AutoEscape
	public String getPublished_at();

	/**
	 * Sets the published_at of this vacancies.
	 *
	 * @param published_at the published_at of this vacancies
	 */
	public void setPublished_at(String published_at);

	/**
	 * Returns the number vacancy of this vacancies.
	 *
	 * @return the number vacancy of this vacancies
	 */
	@AutoEscape
	public String getNumberVacancy();

	/**
	 * Sets the number vacancy of this vacancies.
	 *
	 * @param numberVacancy the number vacancy of this vacancies
	 */
	public void setNumberVacancy(String numberVacancy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(service.model.Vacancies vacancies);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.model.Vacancies> toCacheModel();

	@Override
	public service.model.Vacancies toEscapedModel();

	@Override
	public service.model.Vacancies toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}